# theme: jekyll-theme-architect
   
# Theme
remote_theme: epidrome/cover-card

# Title and tag line
title: 'Florencia Jacobacci'
description: 'Biomedical Engineer'

# Images
avatar: 'FJ.jpg'
background: 'background.jpg'
#favicon: 'favicon.ico'

# Online profiles
linkedin: 'mylinkedin'
github-user: 'mygithub'
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
email: 'hello@example.com'

social-links-order: [github-user, linkedin, email]

# Advanced settings
plugins:
  - jekyll-remote-theme

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: linkedin
    url-pattern: linkedin.com/in/florenciajacobacci/
    
  - name: github-user
    url-pattern: github.com/florjaco
    icon-class: fab fa-2x fa-github

  - name: email
    url-scheme: 'mailto:'
    url-pattern: 'florenciajacobacci@gmail.com'
    icon-class: fas fa-2x fa-envelope


